### ISSUE TITLE
Write Syllabus for a Tufts Experimental College course (possibly based on "Peeragogy in Action" syllabus)

### ISSUE THREAD

**Issue by holtzermann17** [Peeragogy/Peeragogy.github.io#4]
http://peeragogy.github.io/action.html has four steps; are they the right four steps for an Accelerator group to use in a 4-week project?

**Comment by daytripper** [comment]
**What subject or skill does YOUR group want to learn?**
OR
**What product or service does YOUR group want to produce?** 
- identify members & subgroups
- survey members: interests, motivations, skills, experience, time
- other

**What learning theory and practice does the group need to know to put together a successful peer-learning program?** 
OR
**What specific theory and research does the group need to meet production or service goals?** 
- who has gone before? (RRR pattern)
- similar groups & organizations
- best & worst practices
- other similar products, for production
- proven success strategies
- other

**Identify and select the best learning resources about your topic** 
OR
**Identify and select the best production resources for that product or service** 
- published resources
- live resources (people)
- other

**What is the appropriate technology and communications tools and platforms your group needs to accomplish their learning goal?**
OR
**How will these participants identify and select the appropriate technology and communications tools and platforms to accomplish their production goal or service mission?**
- internal platforms & tools including meeting spaces, connecting diverse platforms
- external (public-facing) platforms & tools
- other

**What are your benchmarks for success in your learning enterprise?**
OR
**What are your benchmarks for success in your production enterprise or service organization?**
- survey members
- pilot testing
- formal assessment
- consensus
- other
- what's next?

**Comment by holtzermann17** [comment]
This is excellent - let's integrate it into [the doc I mentioned](https://github.com/Peeragogy/Peeragogy.github.io/blob/master/action.md).

---

Also: I particularly like the cross-reference to the RRR pattern.  Are there other patterns that we should bring in here?  I hope we can spot some.

**Comment by holtzermann17** [comment]
I wrote the course outline and submitted it to Tufts as a proposal. We need to figure out how to integrate it into the Peeragogy  handbook but that can’t be too hard. A first step would be to download the Google Doc as HTML, convert to Markdown and make a wiki page out of that.

**Comment by skreutzer** [comment]
I don't know how this fits in content-wise with the patterization, but technically, Google Docs provides a relatively useful HTML export (download URL). One needs to make sure to remove their evil link rewriting they don't have on Google Docs itself (because there they're already tracking), but on exported data, they add link redirection to still track people despite not using their SaaS crap. I have some code for that, or simply do a replace. What's the point of converting it to Markdown (isn't that just for writing?) if it's already in HTML, except maybe it can run through the regular Markdown to LaTeX conversion via Pandoc, but that may work with HTML as input file as well. Is it about to make the content editable for other contributors working in/on the repository? I guess it depends if you're suggesting a one-time conversion/import or if the repository/Handbook should be updated regularly from the Google Doc. There's also the option to do a simple copy&paste, not throwing automatization tech at it. Other than that, what's the wiki page about? Wikitext, Mediawiki, Federated Wiki, GitHub wiki page?

**Comment by holtzermann17** [comment]
Just a one time update. (This also applies to the reading group versions of
the content, too, to get that integrated into the master copy here.)

Rob Best pointed out HackMD / CodiMD as a tool for synchronous editing of
Markdown, I want to try that too.  It is somehow half way between Google
Docs and what we have in this repo, so maybe a good intermediate step.

This tool does not seem to have marginal comment threads, but we could use
inline comments instead.

Tools to remove Google spam from the HTML would be nice. My computer is not
working right now but I will have a new one in a couple of days.

**Comment by holtzermann17** [comment]
> Other than that, what's the wiki page about? Wikitext, Mediawiki,
Federated Wiki, GitHub wiki page?

Just a staging ground.

**Comment by holtzermann17** [comment]
This was completed.

**Comment by danoff** [comment]
I should've have referenced this issue when creating the [semester two sylabus](https://github.com/Peeragogy/course/blob/master/semester2.md)!
