### ISSUE TITLE
Wrap: Decide where the source gets published/managed/maintained

### ISSUE THREAD

**Issue by skreutzer** [Peeragogy/Peeragogy.github.io#40]
Decide whether the source of the Monthly Wraps should be on Wikiversity or GitHub Wiki, or both, or none, or something else.

**Comment by danoff** [comment]
I think GitHub should the primary source of drafts and then the last draft would be here. And then after the final version is approved, we could move it to Wikiversity.

I like Wikiversity as the public version because we can do interwiki links and it is part of the Wikimedia ecosystem so it can get found by other people there.

**Comment by skreutzer** [comment]
There are some differences between Wikitext (Wikiversity) and Markdown, for example: Wikitext uses server-side "template" plugin syntax for images; Markdown doesn't support footnotes. Still, for now, it was decided to use the GitHub wiki in Markdown until potentially changing to something else later (or not). Ideally, the Wikitext for the replication to Wikiversity might be pre-generated from the GitHub wiki Markdown source, even if it's not complete, but to safe some of the manual work wikification would require.
