### ISSUE TITLE
Reassess use of Markdown

### ISSUE THREAD

**Issue by holtzermann17** [Peeragogy/Peeragogy.github.io#49]
Markdown (`.md`) is the current default master format.

But we should reassess whether it's the best master format for several reasons, e.g.,

- semantic bibliographic formats
- Tufte compatibility with downstream
- easy printing (e.g., import into Indesign for that workflow)
- maybe other issues

**Comment by daytripper** [comment]
I'm here!

**Comment by skreutzer** [comment]
> semantic bibliographic formats

Hmm, Markdown isn't really semantic, doesn't bootstrap its own semantics properly. How does it indicate it's byte order/endian? How does it specify it's character encoding? How does it specify the identity/semantics of its format? Usually there's something like an XML namespace identifier or a JSON-LD `@context` (took the Web crowd only a few years to reinvent that wheel, and it isn't nor can become an inherent feature of the format) to declare what semantics follow, also with the advantage that different semantics (wrapped in the same simple universal structural format convention) can be mixed. I'm not aware that Markdown does any of it, and in its absence, the format and its semantics can only be determined by heuristical analysis, which may fail, and many people don't have `file(1)` installed on their operating systems. Obviously there are many Markdown flavors as well, so I guess the recommendation/request here is to use GitHub Markdown (for the sole reason that it's hosted on GitHub, which may exclude some instructions introduced by other flavors or not play nice in other contexts/processing).

Is the problem here that GitHub Markdown doesn't support bibliographic data to be properly marked up as needed for later processing? I think in general the idea was that Markdown would be simple as a textual writing interface (not necessarily a proper data format), but inevitably all the typical typesetting and Web and document instructions creep in of course, because people conflate the two different purposes, until every format (regardless of what symbol is used for general structuring) converges to the same semantics for marking up a document anyway.

This doesn't mean that other formats are necessarily better, many suffer from the same problems, which is why I don't care that much if it's Markdown or something else, if the alternative is of the same nature and not much of an improvement. Still, Markdown could always be used as a writing interface, we could even introduce our own constructs to cover bibliography and parse/recognize + convert it to target formats, and just because of the "serverless" GitHub Pages via Jekyll setup as a result of the Web hosting, it might not look good on the Website, but that's about it, would be a non-issue if GitHub would not fail to set it up a little bit better.
